# +————————————————————————————————————————————————————+ #
# |——————————     SUPERLOG CONFIGURATION     ——————————| #
# |——————————————————      v1        ——————————————————| #
# +————————————————————————————————————————————————————+ #
# |                   Documentation:                   | #
# |            http://superlog.andross.fr/            | #
# +————————————————————————————————————————————————————+ #

save-delay: 00
date-format: 'yyyy-MM-dd HH:mm:ss'
logsFormat: 'devster7.log'
logsLiveFormat: '&7&o[{TIME}][{EVENT}] {LOG}'
logsInConsole: true
logsInGame: false

gzipLogsAfter: 0
deleteLogs:
  after: 0
  evenGZippedLogs: true

alertCommands:
  - /gamemode
  - /god

messages:
  prefix: '&3&l[&e&lLOG&3&l] '
  noperm: '&cYou don''t have permission.'
  logsSaved: '&7Saved {OCCURRENCES} files.'
  alertCommandsFormat: '&7&l{PLAYER}&7 used: &e{COMMAND}'

events:
  AsyncPlayerChatEvent:
    enabled: true
    message: '{PLAYER} said {MESSAGE}'
  BlockPlaceEvent:
    enabled: true
    message: '{PLAYER} placed {NAME} on [{LOCWORLD};{LOCX};{LOCY};{LOCZ}]'
  BlockBreakEvent:
    enabled: true
    message: '{PLAYER} broke {NAME} on [{LOCWORLD};{LOCX};{LOCY};{LOCZ}]'
